INSERT INTO FACULTY (FACULTY_FNAME, FACULTY_LNAME, FACULTY_PHONE, FACULTY_EMAIL, department_id) VALUES ('Test','Subject',4701111111, 'sample@gmail.com', 1);
INSERT INTO FACULTY (FACULTY_FNAME, FACULTY_LNAME, FACULTY_PHONE, FACULTY_EMAIL, department_id) VALUES ('Guy','Fiery',4701111112,'fiery@gmail.com', 1);
INSERT INTO FACULTY (FACULTY_FNAME, FACULTY_LNAME, FACULTY_PHONE, FACULTY_EMAIL, department_id) VALUES ('Todd','Howard',900111222, 'lies@gmail.com', 2);
INSERT INTO FACULTY (FACULTY_FNAME, FACULTY_LNAME, FACULTY_PHONE, FACULTY_EMAIL, department_id) VALUES ('Adam','Ross',4702221234, 'sample2@gmail.com', 3);

INSERT INTO DEPARTMENT(DEPARTMENT_NAME, DEPARTMENT_EMAIL, DEPARTMENT_PHONE, DEPARTMENT_LOCATION) VALUES ('Communications','communications@ggc.edu',6784075100,'I-1135');
INSERT INTO DEPARTMENT(DEPARTMENT_NAME, DEPARTMENT_EMAIL, DEPARTMENT_PHONE, DEPARTMENT_LOCATION) VALUES ('Information Technology','helpdesk@ggc.edu', 6784075611, 'A-1040');
INSERT INTO DEPARTMENT(DEPARTMENT_NAME, DEPARTMENT_EMAIL, DEPARTMENT_PHONE, DEPARTMENT_LOCATION) VALUES ('Student Integrity', 'studentintegrity@ggc.edu', 6784075661,'E-2150');