INSERT INTO FACULTY (FACULTY_FNAME, FACULTY_LNAME, FACULTY_PHONE, FACULTY_EMAIL) VALUES ('Test','Subject',4701111111, 'sample@gmail.com');
INSERT INTO FACULTY (FACULTY_FNAME, FACULTY_LNAME, FACULTY_PHONE, FACULTY_EMAIL) VALUES ('Guy','Fiery',4701111112,'fiery@gmail.com');
INSERT INTO FACULTY (FACULTY_FNAME, FACULTY_LNAME, FACULTY_PHONE, FACULTY_EMAIL) VALUES ('Todd','Howard',900111222, 'lies@gmail.com');
INSERT INTO FACULTY (FACULTY_FNAME, FACULTY_LNAME, FACULTY_PHONE, FACULTY_EMAIL) VALUES ('Adam','Ross',4702221234, 'sample2@gmail.com');

INSERT INTO DEPARTMENT(DEPARTMENT_NAME, DEPARTMENT_EMAIL, DEPARTMENT_PHONE, DEPARTMENT_LOCATION) VALUES ('Communications','communications@ggc.edu',6784075100,'I-1135');
INSERT INTO DEPARTMENT(DEPARTMENT_NAME, DEPARTMENT_EMAIL, DEPARTMENT_PHONE, DEPARTMENT_LOCATION) VALUES ('Information Technology','helpdesk@ggc.edu', 6784075611, 'A-1040');
INSERT INTO DEPARTMENT(DEPARTMENT_NAME, DEPARTMENT_EMAIL, DEPARTMENT_PHONE, DEPARTMENT_LOCATION) VALUES ('Student Integrity', 'studentintegrity@ggc.edu', 6784075661,'E-2150');