CREATE TABLE FACULTY (
	FACULTY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	FACULTY_FNAME VARCHAR(64),
	FACULTY_LNAME VARCHAR(64),
	FACULTY_PHONE BIGINT,
	FACULTY_EMAIL VARCHAR(255),
	DEPARTMENTID BIGINT

);

CREATE TABLE DEPARTMENT (
	DEPARTMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
	DEPARTMENT_NAME VARCHAR(255),
	DEPARTMENT_EMAIL VARCHAR(255),
	DEPARTMENT_PHONE VARCHAR(255),
	DEPARTMENT_LOCATION VARCHAR(255)

);

ALTER TABLE FACULTY 
	ADD FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENT_ID);