CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	EMPLOYEE_FNAME VARCHAR(64)
	EMPLOYEE_LNAME VARCHAR(64),
	EMPLOYEE_PHONE BIGINT,
	EMPLOYEE_EMAIL VARCHAR,
	

);

CREATE TABLE DEPARTMENT (
	DEPARTMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	DEPARTMENT_NAME VARCHAR,
	DEPARTMENT_EMAIL VARCHAR,
	DEPARTMENT_PHONE VARCHAR,
	DEPARTMENT_LOCATION VARCHAR


);